/**
 * Every call to the backend goes through this module.
 *
 * One place owns the base URL and attaches the Authorization header, so no
 * component has to remember to send the token -- forgetting it in one place
 * would be a silent 401 rather than an obvious bug.
 */

const BASE_URL = import.meta.env.VITE_API_URL || "http://localhost:8000";

/**
 * Turn a failed response into an Error carrying the server's own message.
 *
 * The API returns { detail: "..." } for every error it raises, so the message
 * shown to the user is the one the backend actually produced -- a Cedar parse
 * error reaches the screen unaltered instead of becoming "upload failed".
 */
async function toError(response) {
  let detail = null;
  try {
    detail = (await response.json()).detail;
  } catch {
    // A response with no JSON body, e.g. a proxy error page.
  }

  // Errors raised by the application put a plain string in `detail`. FastAPI's
  // own request-validation errors put an array of field objects there instead,
  // which is not worth showing a user -- fall back to the status in that case.
  const message =
    typeof detail === "string" && detail.trim() !== ""
      ? detail
      : `Request failed (${response.status})`;

  const error = new Error(message);
  error.status = response.status;
  return error;
}

/**
 * fetch, with the bearer token attached and non-2xx turned into a throw.
 */
async function request(path, token, options = {}) {
  const response = await fetch(`${BASE_URL}${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      ...options.headers,
    },
  });

  if (!response.ok) {
    throw await toError(response);
  }
  return response;
}

/** Liveness check. Needs no token. */
export async function getHealth() {
  const response = await fetch(`${BASE_URL}/api/health`);
  if (!response.ok) {
    throw await toError(response);
  }
  return response.json();
}

/** The signed-in user, their customer, and the tenants they may access. */
export async function getMe(token) {
  const response = await request("/api/me", token);
  return response.json();
}

/** Live policy files in one tenant, newest first. */
export async function listPolicies(token, tenantId) {
  const response = await request(`/api/tenants/${tenantId}/policies`, token);
  return response.json();
}

/**
 * Upload a policy file.
 *
 * Content-Type is deliberately not set: the browser adds it along with the
 * multipart boundary, which cannot be generated by hand. Setting it manually
 * produces a request the server cannot parse.
 */
export async function uploadPolicy(token, tenantId, file) {
  const body = new FormData();
  body.append("file", file);

  const response = await request(`/api/tenants/${tenantId}/policies`, token, {
    method: "POST",
    body,
  });
  return response.json();
}

/** Delete a policy file. Returns 204 with no body. */
export async function deletePolicy(token, tenantId, fileId) {
  await request(`/api/tenants/${tenantId}/policies/${fileId}`, token, {
    method: "DELETE",
  });
}

/**
 * Download a policy file and save it to disk.
 *
 * fetch returns data, not a navigation, so the browser has to be told to save
 * it: the bytes become a Blob, the Blob becomes a temporary object URL, and a
 * synthetic link click triggers the download.
 */
export async function downloadPolicy(token, tenantId, fileId, fallbackName) {
  const response = await request(
    `/api/tenants/${tenantId}/policies/${fileId}/content`,
    token,
  );

  const blob = await response.blob();
  const filename = filenameFromResponse(response) || fallbackName;
  saveBlob(blob, filename);
}

/**
 * Read the filename the server chose, from Content-Disposition.
 *
 * Only readable because the API lists that header in CORS expose_headers --
 * without it the browser hides the header from JavaScript and this silently
 * falls back to the name we already had.
 */
function filenameFromResponse(response) {
  const disposition = response.headers.get("Content-Disposition");
  if (!disposition) return null;

  // Quoted form is what this API sends. The unquoted fallback keeps the parse
  // working if the header is ever produced differently.
  const quoted = disposition.match(/filename="([^"]*)"/);
  if (quoted) return quoted[1] || null;

  const unquoted = disposition.match(/filename=([^;]+)/);
  return unquoted ? unquoted[1].trim() : null;
}

function saveBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");

  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();

  // The object URL pins the blob in memory, so it has to be released -- but
  // not immediately. Revoking in the same tick as click() races the browser
  // reading the blob, which can make the download fail or save under the
  // wrong name. Deferring to a later task lets the download start first.
  setTimeout(() => URL.revokeObjectURL(url), 60_000);
}
